### ISSUE TITLE
Loom is undefined.

### ISSUE THREAD

**Issue by Alligatore3** [loomhq/loom-embed#29]
```
yarn add @loomhq/loom-embed
...
import loom from '@loomhq/loom-embed'
...
console.log({ loom }) // { loom: undefined }, why ?
```
Tested with:

```
node -v
v12.18.1

node -v
v13.14.0
```

**Comment by dreynolds** [comment]
I'm getting the same thing too

**Comment by sidraman14** [comment]
Thanks for pointing this out. The import should actually be: 

`import * as loom from '@loomhq/loom-embed'`

We will fix the documentation we have.
