### ISSUE TITLE
[Question] How can I stop redirects a new tab after saving a video? 

### ISSUE THREAD

**Issue by AnubhabMondal** [loomhq/loom-embed#9]
Hi Everyone,
 I just have a question that when we stop recording [ i use loom chrome extension ] that redirects to loom **My videos** library page. 
Is there any way that I can stop redirecting to new tab? If you guys @tpatel @vhmth @acacheung @brendonjohn have some solutions can you please share that would be very helpful.

**Comment by vhmth** [comment]
👋 @AnubhabMondal, if I understand your question correctly, you're asking whether we can change the product experience on Loom so that finishing a video doesn't open a new tab. Is that correct?

**Comment by AnubhabMondal** [comment]
@vhmth  When I finish my recording it automatically copies URL which is awesome. That's why I don't want to automatically redirect to My Video page. I Understand that's good very good features but I don't want this. 
 If there is a way that I can stop redirection that would be very helpful.

**Comment by vhmth** [comment]
@AnubhabMondal I have recorded your feedback to our product managers internally, but there is no current way to change this behavior in our desktop app or Chrome extension currently. Unfortunately, it is not up to me to decide, prioritize and implement this setting, but we will get back to you if this changes.
